### ISSUE TITLE
Subscriber not notified if started after publisher

### ISSUE THREAD

**Issue by goliatone** [mcollina/ascoltatori#119] opened 2015-06-12 17:31 UTC
I'm using the AMQP client. 
I have one publisher that runs in the background sending events to AMQP and multiple subscribers that also run in the background.
Something I've noticed is that if the publisher is running when I launch the subscribers these will not get events. If the subscribers are up before launching the publisher it all works as expected. 
Any ideas?

amqp v0.2.4
ascoltatori v0.20.2
amqp SaaS: http://cloudamqp.com

**Comment by mcollina** [comment] 2015-06-13 08:59
I have always tested this with RabbitMQ locally.

Which version of node are you running? Try setting DEBUG=* before running your tests, and see if anything strange happen (in case, just post the output here)

**Comment by goliatone** [comment] 2015-06-13 15:23
Will do monday when I'm back at work.

**Comment by goliatone** [comment] 2015-06-20 01:23
Ok, it took me a bit longer than planned. There seems to be nothing funny happening...

**Comment by mcollina** [comment] 2015-06-22 09:36
All my tests are passing fine.

Can you please try to reproduce using only https://github.com/mcollina/ascoltatori and in case open an issue there?

**Comment by goliatone** [comment] 2015-07-07 19:47
I was able to reproduce this in a simplified scenario. I also noticed something, if I have multiple clients connected then this is not an issue.

I have two files, `client.js` and `publisher.js`

Scenario A, open two terminal windows, execute a script on each. Let them run for a bit. Then you restart the client. I expect the client to keep getting updates after the restart but it gets stuck there:

```js
goliat at goliatodromo in /tmp/amqp_test
$ node client.js 
CONNECTED
CATCH ALL: connected
CATCH ALL: testing 1
CATCH ALL: testing 2
CATCH ALL: testing 3
CATCH ALL: testing 4
CATCH ALL: testing 5
CATCH ALL: testing 6
CATCH ALL: testing 7
^C

goliat at goliatodromo in /tmp/amqp_test
$ node client.js 
CONNECTED
^C
```

```js
goliat at goliatodromo in /tmp/amqp_test
$ node publisher.js 
NOTIFY CONNECTION
testing 1
testing 2
testing 3
testing 4
testing 5
testing 6
testing 7
testing 8
testing 9
testing 10
testing 11
testing 12
testing 13
testing 14
^C
```

Now, if I restart the publisher instead, it all works as expected:

```js
goliat at goliatodromo in /tmp/amqp_test
$ node publisher.js 
NOTIFY CONNECTION
testing 1
testing 2
testing 3
^C

goliat at goliatodromo in /tmp/amqp_test
$ node publisher.js 
NOTIFY CONNECTION
testing 1
testing 2
testing 3
^C
```

```js
goliat at goliatodromo in /tmp/amqp_test
$ node client.js 
CONNECTED
CATCH ALL: connected
CATCH ALL: testing 1
CATCH ALL: testing 2
CATCH ALL: testing 3
CATCH ALL: connected
CATCH ALL: testing 1
CATCH ALL: testing 2
CATCH ALL: testing 3
^C
```

Now, if I have two clients and one publisher, I can restart clients and they will get back on track:

```js
goliat at goliatodromo in /tmp/amqp_test
$ node publisher.js 
NOTIFY CONNECTION
testing 1
testing 2
testing 3
testing 4
testing 5
testing 6
testing 7
testing 8
^C
```

```js
goliat at goliatodromo in /tmp/amqp_test
$ node client.js A
CONNECTED A
CATCH ALL: connected
CATCH ALL: testing 1
CATCH ALL: testing 2
CATCH ALL: testing 3
CATCH ALL: testing 4
^C

goliat at goliatodromo in /tmp/amqp_test
$ node client.js A
CONNECTED A
CATCH ALL: testing 8
^C
```

```js
goliat at goliatodromo in /tmp/amqp_test
$ node client.js B
CONNECTED B
CATCH ALL: connected
CATCH ALL: testing 1
CATCH ALL: testing 2
CATCH ALL: testing 3
CATCH ALL: testing 4
CATCH ALL: testing 5
CATCH ALL: testing 6
CATCH ALL: testing 7
CATCH ALL: testing 8
^C
```

This are the files:

```js
//client.js
var ascoltatori = require('ascoltatori');

var config = {
    type: 'amqp',
    json: true,
    amqp: require('amqp'),
    exchange: 'wework.dev',
    client: {
        url: 'amqp://xxxxxx-xxx@xxxx.cloudamqp.com/xxxx'
    }
};

ascoltatori.build(config, function (ascoltatore) {
    console.log('CONNECTED', process.argv[2]);
    ascoltatore.subscribe('*', function(topic, message) {
        console.log('CATCH ALL:', topic/*, message*/);
    });
});
```
```js
//publisher.js
var ascoltatori = require('ascoltatori');

var config = {
    type: 'amqp',
    json: true,
    amqp: require('amqp'),
    exchange: 'wework.dev',
    client: {
        url: 'amqp://xxxxxx-xxx@xxxx.cloudamqp.com/xxxx'
    }
};

ascoltatori.build(config, function (ascoltatore) {
    console.log('NOTIFY CONNECTION');
    ascoltatore.pub('connected', {timestamp: Date.now(), from:'goliatodromo'});
    // r.context.pub = ascoltatore.pub.bind(ascoltatore);
    var count = 0;
    setInterval(function(){
        ++count;
        console.log('testing ' + count);
        ascoltatore.pub('testing ' + count);
    },2000);
});
```

**Comment by mcollina** [comment] 2015-07-08 08:20
Can you replicate the same using RabbitMQ, or it is specific to cloudamqp?
The AMQP library Ascoltatori is using is kind of bad, we should probably
rewrite it using amqplib (but I have no time :()

Il giorno mar 7 lug 2015 alle ore 21:47 goliatone <notifications@github.com>
ha scritto:

**Comment by carlhoerberg** [comment] 2015-07-10 08:54
You're using [node-amqp](https://github.com/postwait/node-amqp) which is abandon ware. It can't connect to shared plans on CloudAMQP because of the channel_max limit, which node-amqp doesn't handle. [Amqplib](http://www.squaremobius.net/amqp.node/) is a better maintained AMQP library for nodejs.

**Comment by mcollina** [comment] 2015-07-10 08:55
@carlhoerberg I am perfectly aware of that. Would you like to submit a PR to update from node-amqp to Amqplib? I have no bandwidth to take on that work.

**Comment by goliatone** [comment] 2015-07-10 12:57
@carlhoerberg Could you elaborate your post?
I am using a shared plan for testing, which will get upgraded in the near future. I do not have issues connecting, the issue I see is that I have an- unidirectional- pub/sub scenario. If there is only one subscriber and it disconnects- or restarts- then the next subscriber will connect to the queue but do not receive any messages.

**Comment by mcollina** [comment] 2016-01-19 08:26
Closing for now, please reopen if the problem persists.

**Closed by mcollina** 2016-01-19 08:26 UTC
