### ISSUE TITLE
MongoAscolatori error when publish is handled before 'ready' state

### ISSUE THREAD

**Issue by Arilas** [mcollina/ascoltatori#127] opened 2015-07-20 10:39 UTC
I've use Mosca, and some clients connects just-in-time, when server is up:
So I've see:
```
/...../node_modules/mosca/node_modules/ascoltatori/lib/mongo_ascoltatore.js:114
  this.collection.insert(messageObj, { w: 1 }, done);
                  ^
TypeError: Cannot call method 'insert' of undefined
```
Is it possible to use some queue for this situations? Because I've unable to start server when some devices is trying to connect.

**Comment by mcollina** [comment] 2015-07-20 10:54
Duplicate of https://github.com/mcollina/mosca/issues/317, let's just talk in the Mosca repo.

**Closed by mcollina** 2015-07-20 10:54 UTC
